options {
    directory "/var/cache/bind";
    allow-query { any; };
    allow-recursion { any; };
    recursion yes;
    dnssec-validation no;
    listen-on { any; };
    listen-on-v6 { none; };
    forwarders { 8.8.8.8; 8.8.4.4; };
};
