#!/usr/bin/env python3
"""
ICS-SimLab Extended — Orchestrator

Reads ctf-config.yaml and generates:
  infrastructure/networks/docker-compose.yml   shared zone networks (bring up first)
  zones/enterprise/docker-compose.yml
  zones/operational/docker-compose.yml
  zones/control/docker-compose.yml             9 custom containers (turbine PLC, HMI, IEDs, actuators)
  start.sh
  stop.sh

Usage:
    python orchestrator/generate.py [ctf-config.yaml]
"""

import os
import sys
import re
import logging
import subprocess
import yaml
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(levelname)s - %(message)s")

REPO_ROOT = Path(__file__).resolve().parent.parent
ORCHESTRATOR_DIR = Path(__file__).resolve().parent
ZONES_DIR = REPO_ROOT / "zones"
INFRA_DIR = REPO_ROOT / "infrastructure"
FIREWALL_RULES = ORCHESTRATOR_DIR / "firewall-rules.txt"
ADVERSARY_README = ORCHESTRATOR_DIR / "adversary-readme.txt"

# Maps implementation names to the directory containing their Dockerfile.
# Adding a new component variant means adding an entry here and a Dockerfile.
COMPONENT_DIRS = {
    # internet zone
    "admin-home":              ZONES_DIR / "internet" / "components" / "admin-home",
    # enterprise zone
    "win95-era":               ZONES_DIR / "enterprise" / "components" / "legacy-workstation",
    "enterprise-generic":      ZONES_DIR / "enterprise" / "components" / "enterprise-workstation",
    # operational zone
    "historian-v1":            ZONES_DIR / "operational" / "components" / "historian",
    "scada-generic":           ZONES_DIR / "operational" / "components" / "scada-server",
    "scada-lts":               ZONES_DIR / "operational" / "components" / "scada-lts",
    "engineering-workstation-generic": ZONES_DIR / "operational" / "components" / "engineering-workstation",
    # control zone devices
    "turbine-plc":             ZONES_DIR / "control" / "components" / "turbine-plc",
    "ied-relay":               ZONES_DIR / "control" / "components" / "ied-relay",
    "ied-meter":               ZONES_DIR / "control" / "components" / "ied-meter",
    "hmi":                     ZONES_DIR / "control" / "components" / "hmi",
    "actuator":                ZONES_DIR / "control" / "components" / "actuator",
    "actuator-modbus-sim":     ZONES_DIR / "control" / "components" / "actuator-modbus-sim",
    "mosquitto-broker":        ZONES_DIR / "control" / "components" / "mosquitto-broker",
    "stunnel-gateway":         ZONES_DIR / "control" / "components" / "stunnel-gateway",
    "scada-lts-ctrl":          ZONES_DIR / "control" / "components" / "scada-lts-ctrl",
    "opcua-sidecar":           ZONES_DIR / "control" / "components" / "opcua-sidecar",
    # field devices (deferred — vendor-specific builds)
    # dmz zone
    "umati-gateway":    ZONES_DIR / "dmz" / "components" / "umati-gateway",
    "neuron-gateway":   ZONES_DIR / "dmz" / "components" / "neuron-gateway",
    "mqtt-dmz":         ZONES_DIR / "dmz" / "components" / "mqtt-dmz",
    "opcua-server":     ZONES_DIR / "dmz" / "components" / "opcua-server",
    "iec104-rtu":       ZONES_DIR / "dmz" / "components" / "iec104-rtu",
    "ssh-bastion-vuln": ZONES_DIR / "dmz" / "components" / "ssh-bastion",
    "sftp-drop":        ZONES_DIR / "dmz" / "components" / "sftp-drop",
    "ntp-server":       ZONES_DIR / "dmz" / "components" / "ntp-server",
    "dns-forwarder":    ZONES_DIR / "dmz" / "components" / "dns-forwarder",
    "syslog-relay":     ZONES_DIR / "dmz" / "components" / "syslog-relay",
}


# ---------------------------------------------------------------------------
# Start / stop scripts (static constants — do not customise per-config)
# ---------------------------------------------------------------------------

_START_SH = """\
#!/usr/bin/env bash
# Generated by orchestrator/generate.py — do not edit directly.
set -euo pipefail
REPO="$(cd "$(dirname "$0")" && pwd)"

echo "[*] Creating shared networks..."
docker compose -f "$REPO/infrastructure/networks/docker-compose.yml" up -d

echo "[*] Starting enterprise zone..."
docker compose -f "$REPO/zones/enterprise/docker-compose.yml" up -d

echo "[*] Starting operational zone..."
docker compose -f "$REPO/zones/operational/docker-compose.yml" up -d

echo "[*] Starting control zone..."
docker compose -f "$REPO/zones/control/docker-compose.yml" up -d

echo "[*] Starting DMZ zone..."
docker compose -f "$REPO/zones/dmz/docker-compose.yml" up -d

echo "[*] Applying inter-zone firewall rules..."
if [ "$EUID" -eq 0 ]; then
    bash "$REPO/infrastructure/firewall.sh"
else
    echo "[!] Skipping firewall rules — not root (run as root or with sudo to enforce inter-zone policy)"
fi

echo "[+] All zones running."
"""

_STOP_SH = """\
#!/usr/bin/env bash
# Generated by orchestrator/generate.py — do not edit directly.
set -euo pipefail
REPO="$(cd "$(dirname "$0")" && pwd)"

echo "[*] Stopping DMZ zone..."
docker compose -f "$REPO/zones/dmz/docker-compose.yml" down

echo "[*] Stopping control zone..."
docker compose -f "$REPO/zones/control/docker-compose.yml" down

echo "[*] Stopping operational zone..."
docker compose -f "$REPO/zones/operational/docker-compose.yml" down

echo "[*] Stopping enterprise zone..."
docker compose -f "$REPO/zones/enterprise/docker-compose.yml" down

echo "[*] Removing shared networks..."
docker compose -f "$REPO/infrastructure/networks/docker-compose.yml" down

echo "[*] Flushing inter-zone firewall rules..."
if [ "$EUID" -eq 0 ]; then
    iptables -F DOCKER-USER
    iptables -A DOCKER-USER -j RETURN
else
    echo "[!] Skipping firewall flush — not root (run as root or with sudo to flush rules)"
fi

echo "[+] All zones stopped."
"""


# ---------------------------------------------------------------------------
# Config loading
# ---------------------------------------------------------------------------

def load_config(config_path: Path) -> dict:
    with open(config_path) as f:
        raw = f.read()
    # First pass: parse to get values for template resolution
    partial = yaml.safe_load(raw)
    # Second pass: resolve {{ key.path }} references, then re-parse
    rendered = _render_templates(raw, partial)
    return yaml.safe_load(rendered)


def _render_templates(text: str, config: dict) -> str:
    """Replace {{ dotted.key.path }} references with resolved values from config."""
    def resolve(match):
        path = match.group(1).strip().split(".")
        val = config
        for key in path:
            if isinstance(val, dict) and key in val:
                val = val[key]
            else:
                return match.group(0)  # leave unresolved rather than fail
        return str(val)
    return re.sub(r"\{\{([^}]+)\}\}", resolve, text)


# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------

def _rel(abs_path, base_dir: Path) -> str:
    """Relative path from base_dir to abs_path."""
    return os.path.relpath(str(abs_path), str(base_dir))


def _relativize_services(services: dict, base_dir: Path, resolve_base: Path = None) -> None:
    """Convert build contexts and bind-mount host paths to relative to base_dir.

    If resolve_base is given, existing relative paths are resolved against it
    before being made relative to base_dir — enabling re-relativization from
    one base directory to another.
    """
    def _fix(path_str: str) -> str:
        if not os.path.isabs(path_str):
            if resolve_base is None:
                return path_str
            path_str = str((resolve_base / path_str).resolve())
        return _rel(path_str, base_dir)

    for svc in services.values():
        # build: "/abs/path"  or  build: {context: "/abs/path"}
        if isinstance(svc.get("build"), str):
            svc["build"] = _fix(svc["build"])
        elif isinstance(svc.get("build"), dict) and "context" in svc["build"]:
            svc["build"]["context"] = _fix(svc["build"]["context"])
        # volumes: ["host_path:container_path", ...]
        fixed = []
        for vol in svc.get("volumes", []):
            if isinstance(vol, str) and ":" in vol:
                host, rest = vol.split(":", 1)
                fixed.append(f"{_fix(host)}:{rest}")
            else:
                fixed.append(vol)
        if fixed:
            svc["volumes"] = fixed


# ---------------------------------------------------------------------------
# Network helpers
# ---------------------------------------------------------------------------

def _net(config: dict, key: str) -> str:
    return config["networks"][key]["docker_name"]


def _subnet(config: dict, key: str) -> str:
    return config["networks"][key]["subnet"]


def _external_net(name: str) -> dict:
    return {"external": True, "name": name}


# ---------------------------------------------------------------------------
# Shared networks compose (must start before zone stacks)
# ---------------------------------------------------------------------------

def generate_networks_compose(config: dict) -> dict:
    net_names = [n["docker_name"] for n in config["networks"].values()]
    networks = {}
    for net_cfg in config["networks"].values():
        name = net_cfg["docker_name"]
        networks[name] = {
            "driver": "bridge",
            "name": name,
            "ipam": {"config": [{"subnet": net_cfg["subnet"]}]},
        }
    return {
        "services": {
            "network-init": {
                "image": "alpine:3.19",
                "command": ["/bin/true"],
                "restart": "no",
                "networks": net_names,
            }
        },
        "networks": networks,
    }


# ---------------------------------------------------------------------------
# Enterprise zone
# ---------------------------------------------------------------------------

def generate_enterprise_compose(config: dict, output_path: Path) -> dict:
    ez = config["enterprise_zone"]
    ent_net = _net(config, "enterprise")
    ops_net = _net(config, "operational")
    base_dir = output_path.parent
    services = {}

    # Legacy workstation — enterprise network only.
    # Runs its own services as-built; attack surface is a property of the
    # implementation, not of this config.
    lw = ez["legacy_workstation"]
    _check_impl(lw["implementation"])
    services["legacy-workstation"] = {
        "build": {"context": _rel(COMPONENT_DIRS[lw["implementation"]], base_dir)},
        "container_name": "legacy-workstation",
        "hostname": lw["hostname"],
        "restart": "unless-stopped",
        "networks": {ent_net: {"ipv4_address": lw["ip"]}},
        "cap_add": ["NET_ADMIN"],
    }

    # Enterprise workstation — sits on enterprise AND operational networks.
    # This is the IT/OT convergence point. Dual-homed by design (or rather,
    # by the gradual accumulation of "temporary" network access never revoked).
    ew = ez["enterprise_workstation"]
    _check_impl(ew["implementation"])
    services["enterprise-workstation"] = {
        "build": {"context": _rel(COMPONENT_DIRS[ew["implementation"]], base_dir)},
        "container_name": "enterprise-workstation",
        "hostname": ew["hostname"],
        "restart": "unless-stopped",
        "networks": {
            ent_net: {"ipv4_address": ew["ip"]},
            ops_net: {"ipv4_address": ew["ops_ip"]},
        },
        "cap_add": ["NET_ADMIN"],
    }

    return {
        "services": services,
        "networks": {
            ent_net: _external_net(ent_net),
            ops_net: _external_net(ops_net),
        },
    }


# ---------------------------------------------------------------------------
# TLS certificate generation (for stunnel-gateway / scada-lts)
# ---------------------------------------------------------------------------

def generate_certs(repo_root: Path) -> Path:
    """Generate CA, server, and client certs in <repo_root>/certs/.

    Certs are NOT committed to the repo (.gitignore excludes certs/).
    Anyone who runs generate.py gets fresh certs. Containers mount them
    as read-only volumes; the client key is intentionally chmod 644 by
    the scada-lts entrypoint (CTF vulnerability HEX-5103).

    Returns the certs/ directory path.
    """
    certs_dir = repo_root / "certs"
    ca_key  = certs_dir / "ca.key"
    ca_crt  = certs_dir / "ca.crt"
    srv_key = certs_dir / "server.key"
    srv_crt = certs_dir / "server.crt"
    cli_key = certs_dir / "client.key"
    cli_crt = certs_dir / "client.crt"

    if all(p.exists() for p in [ca_crt, srv_crt, cli_crt]):
        logging.info("Certs already exist, skipping generation.")
        return certs_dir

    certs_dir.mkdir(exist_ok=True)

    subj_ca  = "/CN=UUPL-ModbusCA/O=Unseen University Power and Light Co/C=AM"
    subj_srv = "/CN=uupl-modbus-gw/O=Unseen University Power and Light Co/C=AM"
    subj_cli = "/CN=scadalts-client/O=Unseen University Power and Light Co/C=AM"

    def run(args):
        subprocess.run(args, check=True, capture_output=True)

    logging.info("Generating TLS certs in certs/ ...")

    # CA
    run(["openssl", "genrsa", "-out", str(ca_key), "2048"])
    run(["openssl", "req", "-new", "-x509", "-days", "3650",
         "-key", str(ca_key), "-out", str(ca_crt), "-subj", subj_ca])

    # Server cert (stunnel-gateway)
    srv_csr = certs_dir / "server.csr"
    run(["openssl", "genrsa", "-out", str(srv_key), "2048"])
    run(["openssl", "req", "-new", "-key", str(srv_key),
         "-out", str(srv_csr), "-subj", subj_srv])
    run(["openssl", "x509", "-req", "-days", "730",
         "-in", str(srv_csr), "-CA", str(ca_crt), "-CAkey", str(ca_key),
         "-CAcreateserial", "-out", str(srv_crt)])
    srv_csr.unlink()

    # Client cert (scada-lts)
    cli_csr = certs_dir / "client.csr"
    run(["openssl", "genrsa", "-out", str(cli_key), "2048"])
    run(["openssl", "req", "-new", "-key", str(cli_key),
         "-out", str(cli_csr), "-subj", subj_cli])
    run(["openssl", "x509", "-req", "-days", "3650",
         "-in", str(cli_csr), "-CA", str(ca_crt), "-CAkey", str(ca_key),
         "-CAcreateserial", "-out", str(cli_crt)])
    cli_csr.unlink()

    # Restrict key permissions (gateway entrypoint will chmod server.key; client
    # entrypoint intentionally widens client.key to 644 as the CTF vulnerability)
    srv_key.chmod(0o600)
    cli_key.chmod(0o600)

    logging.info(f"Certs written to {certs_dir}")
    return certs_dir


# ---------------------------------------------------------------------------
# Operational zone
# ---------------------------------------------------------------------------

def generate_operational_compose(config: dict, output_path: Path) -> dict:
    oz = config["operational_zone"]
    ops_net = _net(config, "operational")
    ctrl_net = _net(config, "control")
    base_dir = output_path.parent
    certs_dir = REPO_ROOT / "certs"
    services = {}
    named_volumes = {}

    # Historian — operational network only, reachable from enterprise-workstation
    # via its dual-homed ops_ip.
    hist = oz["historian"]
    _check_impl(hist["implementation"])
    services["historian"] = {
        "build": {"context": _rel(COMPONENT_DIRS[hist["implementation"]], base_dir)},
        "container_name": "historian",
        "hostname": hist["hostname"],
        "restart": "unless-stopped",
        "networks": {ops_net: {"ipv4_address": hist["ip"]}},
        "environment": {
            # Tells the historian which ICS process data to seed at startup.
            # Affects what time-series data is available and what queries return.
            "DATA_SOURCE": hist.get("data_source", config["ics_process"]),
        },
    }

    # SCADA server.
    # scada-lts: Scada-LTS (Mango-based) with stunnel Modbus-TLS client.
    #   Requires a MySQL sidecar (scada-db). Certs volume-mounted from certs/.
    # scada-generic: custom Flask SCADA (original implementation).
    scada = oz["scada_server"]
    _check_impl(scada["implementation"])

    if scada["implementation"] == "scada-lts":
        # MySQL sidecar — backing database for Scada-LTS.
        # Weak credentials (scadalts/scada2015) are discoverable via SQLi or
        # credential dump once the SCADA is compromised.
        named_volumes["scada-db-data"] = {}
        services["scada-db"] = {
            "image": "mysql:8",
            "container_name": "scada-db",
            "hostname": "scada-db",
            "restart": "unless-stopped",
            "networks": {ops_net: {"ipv4_address": "10.10.2.19"}},
            "environment": {
                "MYSQL_DATABASE":      "scadalts",
                "MYSQL_USER":          "scadalts",
                "MYSQL_PASSWORD":      "scada2015",
                "MYSQL_ROOT_PASSWORD": "scadaroot",
            },
            "volumes": ["scada-db-data:/var/lib/mysql"],
        }
        gw_ops_ip = oz.get("stunnel_gateway", {}).get("ops_ip", "10.10.2.50")
        scada_svc = {
            "build": {"context": _rel(COMPONENT_DIRS[scada["implementation"]], base_dir)},
            "container_name": "scada-server",
            "hostname": scada["hostname"],
            "restart": "unless-stopped",
            "networks": {ops_net: {"ipv4_address": scada["ip"]}},
            "environment": {
                "MYSQL_HOST":     "scada-db",
                "MYSQL_PORT":     "3306",
                "MYSQL_DATABASE": "scadalts",
                "MYSQL_USER":     "scadalts",
                "MYSQL_PASSWORD": "scada2015",
                "STUNNEL_GW_IP":  gw_ops_ip,
            },
            "depends_on": ["scada-db"],
            # Mount client cert + key from generated certs/ directory.
            # Key is made world-readable by entrypoint.sh (CTF vuln HEX-5103).
            "volumes": [
                f"{_rel(certs_dir / 'client.crt', base_dir)}:/run/stunnel-certs/client.crt:ro",
                f"{_rel(certs_dir / 'client.key', base_dir)}:/run/stunnel-certs/client.key:ro",
                f"{_rel(certs_dir / 'ca.crt',     base_dir)}:/run/stunnel-certs/ca.crt:ro",
            ],
        }
    else:
        scada_svc = {
            "build": {"context": _rel(COMPONENT_DIRS[scada["implementation"]], base_dir)},
            "container_name": "scada-server",
            "hostname": scada["hostname"],
            "restart": "unless-stopped",
            "networks": {ops_net: {"ipv4_address": scada["ip"]}},
            "environment": {
                "HISTORIAN_IP": scada.get("historian_ip", hist["ip"]),
            },
        }

    services["scada-server"] = scada_svc

    # stunnel-gateway — TLS termination proxy between SCADA and control zone PLCs.
    # Dual-homed: operational (accepts TLS from SCADA) + control (plain Modbus to PLC).
    # Only present when stunnel_gateway is defined in config.
    gw_cfg = oz.get("stunnel_gateway")
    if gw_cfg:
        _check_impl(gw_cfg["implementation"])
        gw_component = COMPONENT_DIRS[gw_cfg["implementation"]]
        services["stunnel-gateway"] = {
            "build": {"context": _rel(gw_component, base_dir)},
            "container_name": "stunnel-gateway",
            "hostname": gw_cfg["hostname"],
            "restart": "unless-stopped",
            "networks": {
                ops_net:  {"ipv4_address": gw_cfg["ops_ip"]},
                ctrl_net: {"ipv4_address": gw_cfg["ctrl_ip"]},
            },
            "environment": {
                "FORWARD_TARGET": gw_cfg.get("forward_to", "10.10.3.21:502"),
            },
            # Mount stunnel.conf template and certs from generated certs/ directory.
            "volumes": [
                f"{_rel(gw_component / 'stunnel.conf',  base_dir)}:/run/stunnel/stunnel.conf:ro",
                f"{_rel(certs_dir / 'ca.crt',           base_dir)}:/run/stunnel/ca.crt:ro",
                f"{_rel(certs_dir / 'server.crt',       base_dir)}:/run/stunnel/server.crt:ro",
                f"{_rel(certs_dir / 'server.key',       base_dir)}:/run/stunnel/server.key:ro",
            ],
        }

    # Engineering workstation — sits on BOTH operational AND control networks.
    # The pivot point into the control zone.
    eng = oz["engineering_workstation"]
    _check_impl(eng["implementation"])
    services["engineering-workstation"] = {
        "build": {"context": _rel(COMPONENT_DIRS[eng["implementation"]], base_dir)},
        "container_name": "engineering-workstation",
        "hostname": eng["hostname"],
        "restart": "unless-stopped",
        "networks": {
            ops_net: {"ipv4_address": eng["ip"]},
            ctrl_net: {"ipv4_address": eng["ctrl_ip"]},
        },
        "environment": {
            # ICS_PROCESS and CONTROL_SUBNET drive what the engineering-workstation
            # has configured: which device IPs are in its config files, what
            # tools are set up, etc.
            "ICS_PROCESS":      eng.get("ics_process", config["ics_process"]),
            "CONTROL_SUBNET":   eng.get("control_network_subnet", _subnet(config, "control")),
        },
        "cap_add": ["NET_ADMIN"],
    }

    compose = {
        "services": services,
        "networks": {
            ops_net:  _external_net(ops_net),
            ctrl_net: _external_net(ctrl_net),
        },
    }
    if named_volumes:
        compose["volumes"] = named_volumes
    return compose


# ---------------------------------------------------------------------------
# Control zone (native — no external simulator dependency)
# ---------------------------------------------------------------------------

def generate_control_compose(config: dict, output_path: Path) -> dict:
    ctrl_net = _net(config, "control")
    base_dir = output_path.parent
    certs_dir = REPO_ROOT / "certs"
    services = {}
    named_volumes = {}

    # Resolve stunnel gateway ctrl IP for scada-lts-ctrl instances.
    gw_ctrl_ip = (
        config.get("operational_zone", {})
              .get("stunnel_gateway", {})
              .get("ctrl_ip", "10.10.3.50")
    )

    for dev in config.get("control_zone", {}).get("devices", []):
        impl = dev["implementation"]
        _check_impl(impl)
        svc_name = dev["name"].replace("_", "-")

        if impl == "scada-lts-ctrl":
            # MySQL sidecar — backing database for the control-zone Scada-LTS.
            db_ip = "10.10.3.11"
            db_svc = f"{dev['name']}-db"
            named_volumes[f"{dev['name']}-db-data"] = {}
            services[db_svc] = {
                "image": "mysql:8",
                "container_name": db_svc,
                "hostname": db_svc,
                "restart": "unless-stopped",
                "networks": {ctrl_net: {"ipv4_address": db_ip}},
                "environment": {
                    "MYSQL_DATABASE":      "scadalts",
                    "MYSQL_USER":          "scadalts",
                    "MYSQL_PASSWORD":      "scada2015",
                    "MYSQL_ROOT_PASSWORD": "scadaroot",
                },
                "volumes": [f"{dev['name']}-db-data:/var/lib/mysql"],
            }
            svc = {
                "build": {"context": _rel(COMPONENT_DIRS[impl], base_dir)},
                "container_name": dev["name"],
                "hostname": dev.get("hostname", dev["name"]),
                "restart": "unless-stopped",
                "networks": {ctrl_net: {"ipv4_address": dev["ip"]}},
                "environment": {
                    "MYSQL_HOST":     db_svc,
                    "MYSQL_PORT":     "3306",
                    "MYSQL_DATABASE": "scadalts",
                    "MYSQL_USER":     "scadalts",
                    "MYSQL_PASSWORD": "scada2015",
                    "STUNNEL_GW_IP":  gw_ctrl_ip,
                    **(dev.get("env") or {}),
                },
                "depends_on": [db_svc],
                "volumes": [
                    f"{_rel(certs_dir / 'client.crt', base_dir)}:/run/stunnel-certs/client.crt:ro",
                    f"{_rel(certs_dir / 'client.key', base_dir)}:/run/stunnel-certs/client.key:ro",
                    f"{_rel(certs_dir / 'ca.crt',     base_dir)}:/run/stunnel-certs/ca.crt:ro",
                ],
            }
        else:
            svc = {
                "build": {"context": _rel(COMPONENT_DIRS[impl], base_dir)},
                "container_name": dev["name"],
                "hostname": dev.get("hostname", dev["name"]),
                "restart": "unless-stopped",
                "networks": {ctrl_net: {"ipv4_address": dev["ip"]}},
            }
            if dev.get("env"):
                svc["environment"] = dev["env"]

        services[svc_name] = svc

        # Sidecars: share parent network namespace (no ip) or get their own IP.
        for sidecar in dev.get("sidecars", []):
            sc_impl = sidecar["implementation"]
            _check_impl(sc_impl)
            sc_name = sidecar["name"].replace("_", "-")
            sc_svc = {
                "build": {"context": _rel(COMPONENT_DIRS[sc_impl], base_dir)},
                "container_name": sidecar["name"],
                "restart": "unless-stopped",
            }
            if "ip" in sidecar:
                sc_svc["hostname"] = sidecar.get("hostname", sidecar["name"])
                sc_svc["networks"] = {ctrl_net: {"ipv4_address": sidecar["ip"]}}
            else:
                sc_svc["network_mode"] = f"service:{svc_name}"
                sc_svc["depends_on"] = [svc_name]
            if sidecar.get("env"):
                sc_svc["environment"] = sidecar["env"]
            services[sc_name] = sc_svc

    compose = {
        "services": services,
        "networks": {ctrl_net: _external_net(ctrl_net)},
    }
    if named_volumes:
        compose["volumes"] = named_volumes
    return compose


# ---------------------------------------------------------------------------
# DMZ zone
# ---------------------------------------------------------------------------

def generate_dmz_compose(config: dict, output_path: Path) -> dict:
    """Generate zones/dmz/docker-compose.yml.

    Iterates dmz_zone.devices. Devices with an enterprise_ip are dual-homed
    on both ics_dmz and ics_enterprise (simulates contractor pivot path).
    """
    dmz_net = _net(config, "dmz")
    ent_net = _net(config, "enterprise")
    base_dir = output_path.parent
    services = {}
    networks_used = {dmz_net}

    for dev in config.get("dmz_zone", {}).get("devices", []):
        impl = dev["implementation"]
        _check_impl(impl)
        svc_name = dev["name"].replace("_", "-")

        networks = {dmz_net: {"ipv4_address": dev["ip"]}}
        if "enterprise_ip" in dev:
            networks[ent_net] = {"ipv4_address": dev["enterprise_ip"]}
            networks_used.add(ent_net)

        svc = {
            "build": {"context": _rel(COMPONENT_DIRS[impl], base_dir)},
            "container_name": dev["name"],
            "hostname": dev.get("hostname", dev["name"]),
            "restart": "unless-stopped",
            "networks": networks,
        }
        if dev.get("env"):
            svc["environment"] = dev["env"]

        if dev.get("syslog_logging"):
            svc["logging"] = {
                "driver": "syslog",
                "options": {
                    "syslog-address": "udp://10.10.5.32:514",
                    "tag": dev.get("hostname", dev["name"]),
                },
            }
            svc.setdefault("depends_on", []).append("syslog-relay")

        services[svc_name] = svc

    return {
        "services": services,
        "networks": {n: _external_net(n) for n in networks_used},
    }


# ---------------------------------------------------------------------------
# Inter-zone firewall (DOCKER-USER chain, applied on the host after zones up)
# ---------------------------------------------------------------------------

def generate_firewall_sh(config: dict) -> str:
    """Generate infrastructure/firewall.sh from orchestrator/firewall-rules.txt.

    The rules file contains iptables commands with {placeholder} addresses.
    Placeholders are resolved from ctf-config.yaml and substituted here.
    Edit firewall-rules.txt to change policy; run 'make generate' afterwards.
    """
    addrs = {
        "internet":      config["networks"]["internet"]["subnet"],
        "enterprise":    config["networks"]["enterprise"]["subnet"],
        "operational":   config["networks"]["operational"]["subnet"],
        "control":       config["networks"]["control"]["subnet"],
        "wan":           config["networks"]["wan"]["subnet"],
        "dmz":           config["networks"]["dmz"]["subnet"],
        "historian":     config["operational_zone"]["historian"]["ip"],
        "scada":         config["operational_zone"]["scada_server"]["ip"],
        "eng_ws":        config["operational_zone"]["engineering_workstation"]["ip"],
        # admin_home internet IP — used for VPN ACCEPT rule before internet→enterprise DROP.
        # Falls back to 0.0.0.0/32 (no-op) when internet_zone is absent from config.
        "admin_home_ip": (
            config.get("internet_zone", {})
                  .get("admin_home", {})
                  .get("internet_ip", "0.0.0.0/32")
        ),
        # ssh-bastion DMZ IP — used for contractor pivot ACCEPT rule before dmz→enterprise DROP.
        # Falls back to 0.0.0.0/32 (no-op) when dmz_zone is absent from config.
        "ssh_bastion": next(
            (d["ip"] for d in config.get("dmz_zone", {}).get("devices", [])
             if d.get("implementation") == "ssh-bastion-vuln"),
            "0.0.0.0/32"
        ),
    }
    # Strip comment header lines from the rules file — the generated script
    # has its own header; the txt file comments are for human editors only.
    raw = FIREWALL_RULES.read_text()
    body = "\n".join(
        line for line in raw.splitlines() if not line.startswith("#")
    ).strip()
    rules = body.format_map(addrs)
    return (
        "#!/usr/bin/env bash\n"
        "# Inter-zone firewall rules — DOCKER-USER chain\n"
        "# Generated by orchestrator/generate.py — do not edit directly.\n"
        "# Edit orchestrator/firewall-rules.txt to change policy.\n"
        "#\n"
        "# Requires root (iptables). Applied after all zone stacks are up.\n"
        "set -euo pipefail\n"
        "\n"
        'if [ "$EUID" -ne 0 ]; then\n'
        '    echo "[firewall] Error: iptables rules require root. Run as root or with sudo." >&2\n'
        "    exit 1\n"
        "fi\n"
        "\n"
        "iptables -F DOCKER-USER\n"
        "\n"
        + rules
        + '\necho "[firewall] Inter-zone rules applied."\n'
    )




# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _check_impl(name: str) -> None:
    if name not in COMPONENT_DIRS:
        raise ValueError(
            f"Unknown implementation/vendor: {name!r}. "
            f"Known: {list(COMPONENT_DIRS)}"
        )


def write_compose(path: Path, compose_dict: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        yaml.dump(compose_dict, f, sort_keys=False, default_flow_style=False)
    logging.info(f"Wrote: {path}")


def write_script(path: Path, content: str) -> None:
    path.write_text(content)
    path.chmod(0o755)
    logging.info(f"Wrote: {path}")


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    logging.info(f"Wrote: {path}")


# ---------------------------------------------------------------------------
# Internet zone (admin-home and any future internet-facing infrastructure)
# ---------------------------------------------------------------------------

def generate_internet_zone_compose(config: dict, output_path: Path) -> dict:
    """Generate zones/internet/docker-compose.yml.

    Contains all internet-zone nodes: attacker machine (unseen-gate) and any
    additional nodes defined in internet_zone (admin_home, future DMZ pivot, etc.).
    """
    inet_net = _net(config, "internet")
    ent_net  = _net(config, "enterprise")
    base_dir = output_path.parent
    services = {}
    networks_used = {inet_net}

    # Attacker machine — always present (defined under attacker_machine in config)
    jh = config["attacker_machine"]
    ssh_host_port = jh.get("ssh_host_port", 22)
    auth_mode = jh.get("auth_mode", "key")
    attacker_dir = ZONES_DIR / "internet" / "components" / "attacker-machine"
    attacker_rel = _rel(attacker_dir, base_dir)

    svc = {
        "build": {"context": attacker_rel},
        "container_name": "attacker-machine",
        "hostname": jh["hostname"],
        "restart": "unless-stopped",
        "networks": {inet_net: {"ipv4_address": jh["internet_ip"]}},
        "ports": [f"{ssh_host_port}:22"],
        # adversary-readme is useful in both modes (mission briefing)
        "volumes": [f"./{attacker_rel}/adversary-readme.txt:/run/adversary-readme.txt:ro"],
    }

    if auth_mode == "password":
        # Password mode: set credentials from config, no key file needed.
        # Used for Root-Me and platforms that publish connection strings.
        accounts = jh.get("accounts", {})
        account_str = " ".join(f"{u}:{p}" for u, p in accounts.items())
        svc["environment"] = {
            "AUTH_MODE": "password",
            "AUTH_ACCOUNTS": account_str,
        }
    else:
        # Key mode (default): pubkey auth, keys mounted at runtime.
        # Used for self-hosted / Hetzner deployments.
        svc["volumes"].insert(
            0, f"./{attacker_rel}/adversary-keys:/run/adversary-keys:ro"
        )

    svc["privileged"] = True  # required to issue mount(2) from inside the container
    services["attacker-machine"] = svc

    # Additional internet-zone nodes (admin_home, etc.)
    iz = config.get("internet_zone", {})
    ah = iz.get("admin_home")
    if ah:
        _check_impl(ah["implementation"])
        services["admin-home"] = {
            "build": {"context": _rel(COMPONENT_DIRS[ah["implementation"]], base_dir)},
            "container_name": "admin-home",
            "hostname": ah["hostname"],
            "restart": "unless-stopped",
            "privileged": True,  # tmpfs mount inside container (OverlayFS has no name_to_handle_at)
            "networks": {
                inet_net: {"ipv4_address": ah["internet_ip"]},
                ent_net:  {"ipv4_address": ah["enterprise_ip"]},
            },
        }
        networks_used.add(ent_net)

    return {
        "services": services,
        "networks": {n: _external_net(n) for n in networks_used},
    }


# ---------------------------------------------------------------------------
# Attacker machine
# ---------------------------------------------------------------------------

def generate_adversary_readme(config: dict) -> str:
    addrs = {
        "enterprise_subnet": config["networks"]["enterprise"]["subnet"],
        "legacy_ws_ip":      config["enterprise_zone"]["legacy_workstation"]["ip"],
        "ent_ws_ip":         config["enterprise_zone"]["enterprise_workstation"]["ip"],
    }
    return ADVERSARY_README.read_text().format_map(addrs)


def generate_jump_host_compose(config: dict, output_path: Path) -> dict:
    inet_net = _net(config, "internet")
    jh = config["attacker_machine"]
    ssh_host_port = jh.get("ssh_host_port", 22)
    return {
        "services": {
            "attacker-machine": {
                "build": {"context": "."},   # relative to compose file dir
                "container_name": "attacker-machine",
                "hostname": jh["hostname"],
                "restart": "unless-stopped",
                "networks": {
                    inet_net: {"ipv4_address": jh["internet_ip"]},
                },
                "ports": [f"{ssh_host_port}:22"],
                "volumes": [
                    "./adversary-keys:/run/adversary-keys:ro",
                    "./adversary-readme.txt:/run/adversary-readme.txt:ro",
                ],
            }
        },
        "networks": {
            inet_net: _external_net(inet_net),
        },
    }


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    config_path = (
        Path(sys.argv[1]) if len(sys.argv) > 1
        else ORCHESTRATOR_DIR / "ctf-config.yaml"
    )

    logging.info(f"Loading config: {config_path}")
    config = load_config(config_path)

    # Generate TLS certs if any zone uses stunnel-gateway or scada-lts.
    oz = config.get("operational_zone", {})
    ctrl_devices = config.get("control_zone", {}).get("devices", [])
    needs_certs = (
        oz.get("stunnel_gateway") or
        oz.get("scada_server", {}).get("implementation") == "scada-lts" or
        any(d["implementation"] == "scada-lts-ctrl" for d in ctrl_devices)
    )
    if needs_certs:
        generate_certs(REPO_ROOT)

    write_compose(
        INFRA_DIR / "networks" / "docker-compose.yml",
        generate_networks_compose(config),
    )

    enterprise_path  = ZONES_DIR / "enterprise"  / "docker-compose.yml"
    operational_path = ZONES_DIR / "operational" / "docker-compose.yml"
    control_path     = ZONES_DIR / "control"     / "docker-compose.yml"

    write_compose(enterprise_path,  generate_enterprise_compose(config, enterprise_path))
    write_compose(operational_path, generate_operational_compose(config, operational_path))
    write_compose(control_path,     generate_control_compose(config, control_path))

    internet_path = ZONES_DIR / "internet" / "docker-compose.yml"
    write_compose(internet_path, generate_internet_zone_compose(config, internet_path))
    write_text(ZONES_DIR / "internet" / "components" / "attacker-machine" / "adversary-readme.txt", generate_adversary_readme(config))

    if config.get("dmz_zone"):
        dmz_path = ZONES_DIR / "dmz" / "docker-compose.yml"
        write_compose(dmz_path, generate_dmz_compose(config, dmz_path))

    write_script(REPO_ROOT / "start.sh", _START_SH)
    write_script(REPO_ROOT / "stop.sh", _STOP_SH)
    write_script(INFRA_DIR / "firewall.sh", generate_firewall_sh(config))

    logging.info("Done. Run: bash start.sh")


if __name__ == "__main__":
    main()
