@version: 4.11
@include "scl.conf"

options {
    keep-hostname(yes);
    time-reopen(10);
};

source s_udp {
    network(
        transport("udp")
        port(514)
    );
};

destination d_file {
    file("/var/log/syslog-relay.log");
};

log {
    source(s_udp);
    destination(d_file);
};
