! UU P&L ent-ops-fw, enterprise/operational L3 boundary.
!
! eth0 = clab out-of-band mgmt. eth1 = ics_enterprise, eth2 = ics_operational.

frr defaults traditional
hostname ent-ops-fw
service password-encryption
no ip forwarding
ip forwarding
!
interface eth1
 description ics_enterprise 10.10.1.0/24
 ip address 10.10.1.202/24
exit
!
interface eth2
 description ics_operational 10.10.2.0/24
 ip address 10.10.2.202/24
exit
!
! Static routes for non-adjacent zones.
ip route 10.10.0.0/24 10.10.1.201
ip route 10.10.5.0/24 10.10.1.201
ip route 10.10.3.0/24 10.10.2.203
ip route 10.10.4.0/24 10.10.2.204
!
enable password uupl-router
!
end
