NFS_Core_Param {
    mount_path_pseudo = true;
    Protocols = 3;
    NFS_Port = 2049;
    MNT_Port = 20048;
}

EXPORT_DEFAULTS {
    Access_Type = RO;
    Squash = All_Squash;
    Protocols = 3;
    SecType = sys;
    Transports = TCP, UDP;
}

EXPORT {
    Export_Id = 1;
    Path = /nfs-export;
    Pseudo = /work;
    Access_Type = RO;
    Squash = All_Squash;
    Protocols = 3;
    Transports = TCP, UDP;
    CLIENT {
        Clients = *;
        Access_Type = RO;
        Squash = All_Squash;
    }
    FSAL {
        Name = VFS;
    }
}

LOG {
    Default_Log_Level = EVENT;
}
